base_config: "config/base.yaml"

experiment:
  type: "spatial_transfer" 
  train_cities: ["ANTWERP", "BANGKOK", "MOSCOW"]
  test_cities: ["BARCELONA", "MELBOURNE"]
  years: ["2019", "2020"]
  random_seed: 42
  val_fraction: 0.1

logging:
  experiment_name: "spatial_transfer_experiment"

training:
  batch_size: 4
  epochs: 50