# config/debug.yaml
# Debug configuration supporting all experiment types including enhanced spatio-temporal

base_config: "config/base.yaml"

data:
  limit_per_split: 100
  cities: ["BARCELONA", "MELBOURNE", "ANTWERP"]

training:
  batch_size: 2
  epochs: 3
  num_workers: 0  # For debugging compatibility

# # Default experiment (can be overridden)
# experiment:
#   type: "spatial_transfer"
#   train_cities: ["ANTWERP"]
#   test_cities: ["BARCELONA"]
#   random_seed: 42
#   val_fraction: 0.1

# logging:
#   experiment_name: "debug_experiment"
#   log_interval: 5

# Enhanced Spatio-Temporal Transfer Debug Configuration
# Use this by setting experiment.type to "enhanced_spatiotemporal_transfer"

experiment:
  type: "enhanced_spatiotemporal_transfer"
  
  # Minimal training data
  train_cities: ["ANTWERP"]
  train_years: ["2019"]
  
  # Target city for transfer
  test_city: "BARCELONA" 
  test_train_year: "2019"
  test_target_year: "2020"
  
  # Few-shot adaptation
  adaptation_samples: 10
  
  # Dataset info (computed automatically)
  num_cities: 1
  num_years: 1
  
  random_seed: 42
  val_fraction: 0.1

model:
  name: "multitask_unet"
  in_channels: 96
  out_channels: 48
  features: [32, 64, 128]  # Smaller for debug
  use_attention: true
  use_meta_learning: true

training:
  # Multi-task loss weights
  traffic_weight: 1.0
  city_weight: 0.1
  year_weight: 0.1
  enhanced_traffic_weight: 0.5

logging:
  experiment_name: "debug_enhanced_spatiotemporal"