# config/debug_enhanced_spatiotemporal.yaml
# Debug configuration for enhanced spatio-temporal transfer

base_config: "config/spatiotemporal_config.yaml"

data:
  limit_per_split: 20        # Very small for quick testing
  cities: ["BARCELONA", "MELBOURNE", "ANTWERP"]  # Minimal cities

training:
  batch_size: 1              # Minimal batch size
  epochs: 2                  # Just 2 epochs for testing
  num_workers: 0             # No multiprocessing for debugging

experiment:
  type: "enhanced_spatiotemporal_transfer"
  
  # Minimal setup for debugging
  train_cities: ["ANTWERP"]           # Single training city
  train_years: ["2019"]               # Single year
  test_city: "BARCELONA"              # Different city
  test_train_year: "2019"             # Same year for adaptation
  test_target_year: "2020"            # Different year for testing
  
  adaptation_samples: 5               # Very few adaptation samples
  comprehensive_analysis: false       # No comprehensive analysis in debug

logging:
  experiment_name: "debug_enhanced_spatiotemporal"
  log_interval: 2